name: Go

on:
  pull_request:
    branches: [ main ]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: check assets are up to date
      run: |
        go run main.go > output/index.html
        if [ $(git diff | wc -l) != 0 ]; then
          echo 'changes detected'
          exit 1;
        fi;
